### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by mxa** [SpotlightKid/jack-select#8]
Didn't know where to ask, so I'll do it in an issue:
Which method would you recommend to make sure jack-select is run on every system startup?

**Comment by SpotlightKid** [comment]
I just link the `jack-select.desktop` file to the desktop autostart folder (` ~/.config/autostart`) as described in the [README](../blob/master/README.md). Some desktop environments have a GUI program to add programs to the autostart folder, for example Xfce4 has `xfce4-session-settings`.

If you want to activate a specific preset when `jack-select` starts, *copy* the `jack-select.desktop` file to the autostart folder instead of linking it and edit the `Exec` line and add the name of the preset as a command line argument. Again, some desktop environments have a GUI to edit `.desktop` files, e.g. `lxshortcut` for LXDE or `exo-desktop-item-edit` for Xfce4. KDE probably has matching tools as well.

**Comment by mxa** [comment]
The README only specifies how to autostart the version installed from git, but as far as I can see there is no jack-select.desktop file when the release version is installed through the python package manager.

**Comment by SpotlightKid** [comment]
The "official" way to install `jack-select` is via `make install` (or distribution packages), either from a git repo checkout or from the unpacked source distribution. `jack-select` is an application, not only a Python package; pip does not provide support for installing files for desktop integration or other support files (icons, man pages, etc.).

**Comment by mxa** [comment]
For the record, it's possible to install `jack-select` via `pip3` and then make the desktop file manually to  autostart like this: https://stackoverflow.com/a/25805612/1964109

**Comment by SpotlightKid** [comment]
You can also use the `gendesk` utility to generate desktop files:

https://gendesk.roboticoverlords.org/

Some Linux distros (e.g. Arch) [have this packaged](https://www.archlinux.org/packages/community/x86_64/gendesk/).
